"""Policy engine — access control, red-line enforcement, AI Act disclosure."""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

from ..consent.models import ConsentMode, RedLine
from ..consent.store import ConsentStore


class PolicyDecision(BaseModel):
    allowed: bool
    directive_id: Optional[str] = None
    red_lines_violated: list[str] = []
    ai_disclosure: str = ""
    reason: str = ""


class PolicyEngine:
    """Checks consent, red lines, and AI Act Article 50 disclosure."""

    def __init__(self, consent_store: ConsentStore):
        self.consent_store = consent_store

    def check_access(
        self,
        donor_id: str,
        mode: ConsentMode,
        interactant_id: Optional[str] = None,
        question: str = "",
    ) -> PolicyDecision:
        """Full access check: consent + red lines + disclosure."""
        consent = self.consent_store.check_consent(
            donor_id=donor_id,
            mode=mode,
            interactant_id=interactant_id,
        )

        if not consent.allowed:
            return PolicyDecision(
                allowed=False,
                reason=consent.reason,
                ai_disclosure=self.format_ai_disclosure(mode),
            )

        # Check red lines
        violated = self.check_red_lines(question, consent.red_lines)
        if violated:
            return PolicyDecision(
                allowed=False,
                directive_id=consent.directive_id,
                red_lines_violated=violated,
                reason=f"Red line violated: {', '.join(violated)}",
                ai_disclosure=self.format_ai_disclosure(mode),
            )

        return PolicyDecision(
            allowed=True,
            directive_id=consent.directive_id,
            ai_disclosure=self.format_ai_disclosure(mode),
            reason="Access granted",
        )

    def check_red_lines(self, question: str, red_lines: list[RedLine]) -> list[str]:
        """Return descriptions of any red lines violated by the question."""
        if not question or not red_lines:
            return []
        q_lower = question.lower()
        violated = []
        for rl in red_lines:
            # Simple keyword check — hard red lines only
            if rl.severity == "hard" and rl.description.lower() in q_lower:
                violated.append(rl.description)
        return violated

    def format_ai_disclosure(self, mode: ConsentMode) -> str:
        """AI Act Article 50 disclosure label."""
        labels = {
            ConsentMode.ARCHIVE: (
                "You are viewing archived recordings. "
                "No AI generation is involved."
            ),
            ConsentMode.CONSTRAINED_AVATAR: (
                "This response was generated by AI based on the donor's "
                "recorded answers. It is not the donor speaking."
            ),
            ConsentMode.SIMULATION_AGENT: (
                "This is a fully AI-generated interaction. "
                "The character is synthetic and does not represent "
                "the real person's views."
            ),
        }
        return labels.get(mode, "AI-generated content.")
